server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: web.smxy.xyz
                port: 5672
                username: admin
                password: admin
      bindings:
        output:
          destination: studyExchange
          content-type: application/json
          binder:defaultRabbit

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 5
    instance-id: send-8801.com
    prefer-ip-address: true
